language: node_js
node_js :
 - "node"
after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: never
services:
 - postgresql
before_script:
  - psql -c 'CREATE DATABASE doggo_booker;' -U postgres
  - psql -c "CREATE USER mackerel WITH PASSWORD 'flipflop';" -U postgres
  - psql -c "ALTER DATABASE doggo_booker OWNER TO mackerel;" -U postgres
